### ISSUE TITLE
misc fixes to review

### ISSUE THREAD

**Issue by ntadimeti** [clara-genomics/AtacWorks#106]
1. train.py - Whether we need the print statement of `time breakdown for epochs` in the end
2. print_rank_0 in utils.py
3. definition of rank.

**Comment by ntadimeti** [comment]
@tijyojwad  can you comment on the above three issues I mentioned ?

**Comment by tijyojwad** [comment]
Rank is the index number associated with a GPU

Print_rank_0 only prints messages from the process that's running on GPU 0. It helps make the output more readable.

Time breakdown per epoch is nice to have

**Comment by ntadimeti** [comment]
addressed
