### ISSUE TITLE
Save data in named Numpy fields

### ISSUE THREAD

**Issue by avantikalal** [clara-genomics/AtacWorks#13]
- name Numpy fields as noisy_data, clean_data, clean_peaks
- saving noisy data is not required once dynamic downsampling is merged.
- edit all data loading accordingly
- edit calculate_baseline_metrics accordingly

**Comment by tijyojwad** [comment]
New feature to be added to this request - 

Right now information about like the dataset like padding is supplied as command line parameters to different scripts in the pipeline. But this metadata should be stored with the dataset at time of generation so downstream scripts can read it from the dataset directly without depending on explicitly passed arguments. This request is to add the metadata section to the .h5 and use it in various scripts.
