### ISSUE TITLE
Eliminate postprocessing by writing directly to bigWig

### ISSUE THREAD

**Issue by avantikalal** [clara-genomics/AtacWorks#39]
Can we write inference results directly to bigWig format in `main.py`? This eliminates `postprocess.py`, saves disk space and time spent in I/O of intermediate files. Should be possible using `pyBigWig` functions.

**Comment by ntadimeti** [comment]
Done. This leads to slow perf because writing out bedgraph isn't parallelized. Opening another PR to address the perf issues.
