### ISSUE TITLE
[README] Step by step example

### ISSUE THREAD

**Issue by tijyojwad** [clara-genomics/AtacWorks#44]
Add step by step example for training and inference
Redirect to example scripts for each of them in example folder

**Comment by ntadimeti** [comment]
update : split example/run.sh into training and inference scripts at the minimum.

**Comment by avantikalal** [comment]
Apart from the default options in `run.sh` , also include a description of various other options available for training and inference and how to use them. For example, changing the loss function and weights, changing the metric to select the best model.
