### ISSUE TITLE
[workflow] pipeline atacworks to overlap inference and post processing

### ISSUE THREAD

**Issue by tijyojwad** [clara-genomics/AtacWorks#46]
Pipeline AtacaWorks workflow to run multiple batches simultaneously.

1. Inference --- PostProcess
                          2. Inference   ---  PostProcess   
                                                      3. Inference   ---  PostProcess

**Comment by avantikalal** [comment]
Can this be closed?

**Comment by tijyojwad** [comment]
Yes, this feature has been invalidated with https://github.com/clara-genomics/AtacWorks/pull/51 which combined postprocess and main into a single step
