### ISSUE TITLE
Organize main.py command line arguments into config file

### ISSUE THREAD

**Issue by ntadimeti** [clara-genomics/AtacWorks#54]
Currently main.py takes in a lot of arguments for various functionalities and it can get confusing for first-time users. Proposal is to organize the main.py help arguments into 3 main categories. train, eval and infer. For example python main.py --infer_help will print only arguments relevant to inference.

**Comment by tijyojwad** [comment]
Here's an example of how that can be done with python argparse - https://chase-seibert.github.io/blog/2014/03/21/python-multilevel-argparse.html

**Comment by tijyojwad** [comment]
Updating this task to cover redesigning of option parsing from command line only to command line + config file.

**Comment by ntadimeti** [comment]
#89 addresses this
