### ISSUE TITLE
[main.py] Add parallelization to writing out bedGraph files

### ISSUE THREAD

**Issue by ntadimeti** [clara-genomics/AtacWorks#57]
Inference results are being saved to bedGraph files. This happens in a serial fashion and is very slow. On a large dataset inference on GPU take 10 minutes and 90 minutes are spent on writing out the results. This can be parallelized and made significantly faster.

**Comment by tijyojwad** [comment]
@ntadimeti changes were checking in with #62 . Anything else left on on this?

**Comment by ntadimeti** [comment]
Nothing else, this can be closed. We can open another issue if we want to look into bringing the inference time even down ? Not sure if that's necessary ?

**Comment by tijyojwad** [comment]
Sounds good, no need to create a new issue now. Closing this one. Thanks @ntadimeti !
