### ISSUE TITLE
Store model metadata along with model file

### ISSUE THREAD

**Issue by avantikalal** [clara-genomics/AtacWorks#7]
Right now when a model is loaded for inference the main.py script needs the same arguments for model dimensions as was passed during the training of the model. This is cumbersome since the user needs to keep track of the model arch separately.
We need to have a way of either storing the model metadata along with the model, or of inferring the model architecture from the pre trained model directly.

**Comment by ntadimeti** [comment]
Addressed by PR: https://github.com/clara-genomics/AtacWorks/pull/83

**Comment by ntadimeti** [comment]
merged #83
