### ISSUE TITLE
[main] Fix API documentation

### ISSUE THREAD

**Issue by tijyojwad** [clara-genomics/AtacWorks#86]
Everytime we update a function signature, we risk outdating the documentation of the function. We already have several functions that are either outdated or have no documentation at all. We need fix this in an automated fashion. One way to go about it is to apply documentation checker for the source code as part of CI. This will ensure that any update to our APIs is accompanied by the corresponding documentation change.

There are several tools out there to do this. One possible methodology would be -
1. Standardize on docstring style (google docstring style seems to be a consensus online)
2. Add docstring checker for the source code (e.g. `pydocstyle --convention=google .`)
3. Auto documentation generation (e.g. using Sphinx https://gisellezeno.com/tutorials/sphinx-for-python-documentation.html)

**Comment by ntadimeti** [comment]
done.
